# **Question-11**

In [12]:
#Question-11
import numpy as np

#******************************************** (a) ***************************************
# Define the coefficients matrix (A)
A = np.array([[3, -1, 1],
              [3, 6, 2],
              [3, 3, 7]])

# Definethe constants vector (b)
b = np.array([1, 0, 4])

# Solve the system of linear equations
x = np.linalg.solve(A, b)

print("Solution(a):")
print(x)
print()


#******************************************** (b) ***************************************
# Define the coefficients matrix (A)
A = np.array([[10, -1, 0],
              [-1, 10, -2],
              [0, -2, 10]])

# Definethe constants vector (b)
b = np.array([9, 7, 6])

# Solve the system of linear equations
x = np.linalg.solve(A, b)

print("Solution(b):")
print(x)
print()


#******************************************** (c) ***************************************
# Define the coefficients matrix (A)
A = np.array([[10, 5, 0, 0],
              [5, 10, -4, 0],
              [0, -4, 8, -1],
              [0, 0, -1, 5]])

# Definethe constants vector (b)
b = np.array([6, 25, -11, -11])

# Solve the system of linear equations
x = np.linalg.solve(A, b)

print("Solution(c):")
print(x)
print()


#******************************************** (d) ***************************************
# Define the coefficients matrix (A)
A = np.array([[4, 1, 1, 0, 1],
              [-1, -3, 1, 1, 0],
              [2, 1, 5, -1, -1],
              [-1, -1, -1, 4, 0],
              [0, 2, -1, 1, 4]])

# Definethe constants vector (b)
b = np.array([6, 6, 6, 6, 6])

# Solve the system of linear equations
x = np.linalg.solve(A, b)

print("Solution(d):")
print(x)

Solution(a):
[ 0.03508772 -0.23684211  0.65789474]

Solution(b):
[0.99578947 0.95789474 0.79157895]

Solution(c):
[-0.79764706  2.79529412 -0.25882353 -2.25176471]

Solution(d):
[ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]


# **Question-16**

In [69]:
#Question-16
import numpy as np

#Defining the coefficients matrix (A)
A=np.array([[0.2, 0.1, 1, 1, 0],
            [0.1, 4, -1, 1, -1],
            [1, -1, 60, 0, -2],
            [1, 1, 0, 8, 4],
            [0, -1, -2, 4, 700]]).astype(float)

#Defining the vector b
b=np.array([1, 2, 3, 4, 5]).astype(float)

#Defining the correct solution
xt = np.array([7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163])

#Defining initial guess
x0=np.array([0,0,0,0,0]).astype(float)

In [70]:
#Solution using Jacobi method

#Defining function for Jacobi method
def jacobi(A, b, x0, tol=0.01, max=100):
    n = len(A)
    U = -np.triu(A,k=1)
    L = -np.tril(A,k=-1)
    D = A + U + L
    T = np.matmul(np.linalg.inv(D),np.add(L,U))
    C = np.matmul(np.linalg.inv(D),b)
    x = np.copy(x0)
    for k in range(max):
        x_old = np.copy(x)
        x = np.add(np.matmul(T,x),C)
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
    raise ValueError("Jacobi method did not converge")

#Solving the given system
solution = jacobi(A, b, x0)
print("Solution using Jacobi method:", solution[0])
print("Number of iterations:", solution[1])

Solution using Jacobi method: [ 7.86798447  0.4239069  -0.0731638  -0.5370925   0.01063184]
Number of iterations: 39


In [73]:
#Solution using Gauss-Seidel method

#Defining function for Gauss-Seidel method
def gauss_seidel(A, b, x0, tol=0.01, max=1000):
    n = len(A)
    U = -np.triu(A,k=1)
    L = -np.tril(A,k=-1)
    D = A + U + L
    T = np.matmul(np.linalg.inv(np.add(D,-L)),U)
    C = np.matmul(np.linalg.inv(np.add(D,-L)),b)
    x = np.copy(x0)
    for k in range(max):
        x_old = np.copy(x)
        x = np.add(np.matmul(T,x),C)
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
    raise ValueError("Gauss-Seidel method did not converge")

#Solving the given system
solution = gauss_seidel(A, b, x0)
print("Solution using Gauss-Seidel method:", solution[0])
print("Number of iterations:", solution[1])

Solution using Gauss-Seidel method: [ 7.85091478  0.42280131 -0.07344797 -0.53952326  0.01062   ]
Number of iterations: 18


In [74]:
#Solution using Relaxation method

#Defining function for Relaxation method
def relaxation(A, b, x0, tol=0.01, max=1000, omega=1.25):
    n = len(b)
    x = np.copy(x0)
    for k in range(max):
        x_old = np.copy(x)
        for i in range(n):
            sum = 0
            for j in range(n):
                if j != i:
                    sum += A[i][j] * x[j]
            x[i] = (1 - omega) * x_old[i] + (omega / A[i][i]) * (b[i] - sum)
        r = np.multiply(np.diag(A),np.add(x,-x_old))
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
    raise ValueError("Relaxation method did not converge")

solution = relaxation(A, b, x0)
print("Solution using Relaxation method:", solution[0])
print("Number of iterations:", solution[1])

Solution using Relaxation method: [ 7.85152701  0.42277371 -0.07348303 -0.53978369  0.01062286]
Number of iterations: 7


In [76]:
#Solution using Conjugate Gradient method

#Defining function for Conjugate Gradient method
def conjugate(A, b, x0, tol=0.01, max=1000):
    r = b - np.dot(A, x0)
    p = np.copy(r)
    x = np.copy(x0)
    rsold = np.dot(r, r)
    for k in range(max):
        Ap = np.dot(A, p)
        alpha = rsold / np.dot(p, Ap)
        x = x + alpha * p
        if np.linalg.norm(x - xt) < tol:
            return x,k+1
        r = r - alpha * Ap
        rsnew = np.dot(r, r)
        beta = (rsnew / rsold)
        p = r + beta * p
        rsold = np.copy(rsnew)
    raise ValueError("Relaxation method did not converge")

solution = conjugate(A, b, x0)
print("Solution using Conjugate Gradient method:", solution[0])
print("Number of iterations:", solution[1])


Solution using Conjugate Gradient method: [ 7.85971308  0.42292641 -0.07359224 -0.54064302  0.01062616]
Number of iterations: 5


# **Question-17**

In [22]:
#Question-17
import numpy as np

#Defining function for eigenvalues using QR decomposition
def qr_eigen(A, max=100, tol=1e-5):
    n = A.shape[0]
    V = np.eye(n)

    for _ in range(max):
        Q, R = np.linalg.qr(A)
        A = np.dot(R, Q)
        V = np.dot(V, Q)
        if np.abs(A.diagonal(-1)).max() < tol:
            break

    eigenvalues = A.diagonal()
    return eigenvalues, V

#Defining the matrix A
A=np.array([[5,-2],
            [-2,8]])

#Evaluating the eigenvalues using QR decomposition
eigenvalues, eigenvectors = qr_eigen(A)
print("Eigenvalues using QR decomposition:")
print(eigenvalues)
print()

#Evaluating the eigenvalues using numpy.linalg.eigh
eigenvalues2, eigenvectors2=np.linalg.eigh(A)
print("Eigenvalues using numpy.linalg.eigh:")
print(eigenvalues2)

#*********************Comparison of results: The eigenvalues that we obtain are the same from both the methods.**********************

Eigenvalues using QR decomposition:
[9. 4.]

Eigenvalues using numpy.linalg.eigh:
[4. 9.]


# **Question-18**

In [38]:
#Question-18
import numpy as np

#Defining function for power method
def powmeth(A, max=1000, tol=0.01):
    n = A.shape[0]
    x = np.random.rand(n)
    x /= np.linalg.norm(x)
    ev0 = 0

    for k in range(max):
        xn = np.matmul(A, x)
        ev = np.dot(xn, x)
        xn /= np.linalg.norm(xn)

        if abs(ev0 - ev)/ev < tol:
            break

        x = xn
        ev0 = ev

    return ev

#Defining the given matrix A
A = np.array([[2,-1,0],
              [-1,2,-1],
              [0,-1,2]])

#Evaluating the dominant eigenvalue
eigenvalue = powmeth(A)

print("Dominant eigenvalue=", eigenvalue)

Dominant eigenvalue= 3.414116831658673


# **Question-19**

In [64]:
#Question-19-(a)
import numpy as np

#Defining the given matrix
A = np.array([[2, 1],
              [1, 0]])

#Defining the S-matrix
def sigma(sv, m, n):
    Sigma = np.zeros((m, n))

    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(sv)

    return Sigma

#Singular Value Decomposition
U,S,Vt=np.linalg.svd(A)
Sigma = sigma(S,U.shape[1],Vt.shape[1])
print("Solution for part (a):")
print()
print("U matrix:")
print(U)
print("\nS matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

#Demonstration that the decomposition is correct
A1 = np.dot(np.dot(U,Sigma),Vt)
print("\nProduct of decomposed matrices:")
print(A1)

#Time taken by computation: 1 second

Solution for part (a):

U matrix:
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]

S matrix:
[[2.41421356 0.        ]
 [0.         0.41421356]]

V transpose matrix:
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

Product of decomposed matrices:
[[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -3.81016887e-17]]


In [65]:
#Question-19-(b)
import numpy as np

#Defining the given matrix
A = np.array([[2, 1],
              [1, 0],
              [0, 1]])

#Defining the S-matrix
def sigma(sv, m, n):
    Sigma = np.zeros((m, n))

    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(sv)

    return Sigma

#Singular Value Decomposition
U,S,Vt=np.linalg.svd(A)
Sigma = sigma(S,U.shape[1],Vt.shape[1])
print("Solution for part (b):")
print()
print("U matrix:")
print(U)
print("\nS matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

#Demonstration that the decomposition is correct
A1 = np.dot(np.dot(U,Sigma),Vt)
print("\nProduct of decomposed matrices:")
print(A1)

#Time taken by computation: 1 second

Solution for part (b):

U matrix:
[[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]

S matrix:
[[2.44948974 0.        ]
 [0.         1.        ]
 [0.         0.        ]]

V transpose matrix:
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

Product of decomposed matrices:
[[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -6.81060746e-17]
 [-1.23617226e-16  1.00000000e+00]]


In [66]:
#Question-19-(c)
import numpy as np

#Defining the given matrix
A = np.array([[2, 1],
              [-1, 1],
              [1, 1],
              [2, -1]])

#Defining the S-matrix
def sigma(sv, m, n):
    Sigma = np.zeros((m, n))

    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(sv)

    return Sigma

#Singular Value Decomposition
U,S,Vt=np.linalg.svd(A)
Sigma = sigma(S,U.shape[1],Vt.shape[1])
print("Solution for part (c):")
print()
print("U matrix:")
print(U)
print("\nS matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

#Demonstration that the decomposition is correct
A1 = np.dot(np.dot(U,Sigma),Vt)
print("\nProduct of decomposed matrices:")
print(A1)

#Time taken by computation: 1 second

Solution for part (c):

U matrix:
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]

S matrix:
[[3.16227766 0.        ]
 [0.         2.        ]
 [0.         0.        ]
 [0.         0.        ]]

V transpose matrix:
[[-1. -0.]
 [-0. -1.]]

Product of decomposed matrices:
[[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]


In [67]:
#Question-19-(d)
import numpy as np

#Defining the given matrix
A = np.array([[1, 1, 0],
              [-1, 0, 1],
              [0, 1, -1],
              [1, 1, -1]])

#Defining the S-matrix
def sigma(sv, m, n):
    Sigma = np.zeros((m, n))

    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(sv)

    return Sigma

#Singular Value Decomposition
U,S,Vt=np.linalg.svd(A)
Sigma = sigma(S,U.shape[1],Vt.shape[1])
print("Solution for part (d):")
print()
print("U matrix:")
print(U)
print("\nS matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

#Demonstration that the decomposition is correct
A1 = np.dot(np.dot(U,Sigma),Vt)
print("\nProduct of decomposed matrices:")
print(A1)

#Time taken by computation: 2 seconds

Solution for part (d):

U matrix:
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01  3.33066907e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  3.33066907e-16 -5.55111512e-17  7.55928946e-01]]

S matrix:
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]]

V transpose matrix:
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]

Product of decomposed matrices:
[[ 1.00000000e+00  1.00000000e+00  2.52368982e-17]
 [-1.00000000e+00  1.27610516e-17  1.00000000e+00]
 [-8.05746207e-17  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]


In [68]:
#Question-19-(e)
import numpy as np

#Defining the given matrix
A = np.array([[0, 1, 1],
              [0, 1, 0],
              [1, 1, 0],
              [0, 1, 0],
              [1, 0, 1]])

#Defining the S-matrix
def sigma(sv, m, n):
    Sigma = np.zeros((m, n))

    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(sv)

    return Sigma

#Singular Value Decomposition
U,S,Vt=np.linalg.svd(A)
Sigma = sigma(S,U.shape[1],Vt.shape[1])
print("Solution for part (e):")
print()
print("U matrix:")
print(U)
print("\nS matrix:")
print(Sigma)
print("\nV transpose matrix:")
print(Vt)

#Demonstration that the decomposition is correct
A1 = np.dot(np.dot(U,Sigma),Vt)
print("\nProduct of decomposed matrices:")
print(A1)

#Time taken by computation: 2 seconds

Solution for part (e):

U matrix:
[[-5.47722558e-01  3.50476164e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.48383873e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01 -7.02388902e-17 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.71841615e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01 -8.16496581e-01  2.43277252e-16  1.32058463e-01
   4.27271064e-01]]

S matrix:
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

V transpose matrix:
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-5.77350269e-01  5.77350269e-01 -5.77350269e-01]
 [-7.07106781e-01 -3.88578059e-16  7.07106781e-01]]

Product of decomposed matrices:
[[-1.88904597e-16  1.00000000e+00  1.00000000e+00]
 [-7.58392910e-17  1.00000000e+00 -7.62142974e-17]
 [ 1.00000000e+00  1.00000000e+00 -3.4